amazon-inspector:
    IN-MAL-: IN-MAL-2025-000001.json
ossf-package-analysis:
    confident/: confident/20251026/130445-npm-near-abi-client-js-1.1.0.json
reversing-labs:
    RLMA-: RLMA-2025-05558.json
    RLUA-: RLUA-2025-05510.json
