amazon-inspector:
    IN-MAL-: IN-MAL-2025-000141.json
ossf-package-analysis:
    confident/: confident/20251029/181101-npm-ect-987654-0.0.1.json
reversing-labs:
    RLMA-: RLMA-2025-05558.json
    RLUA-: RLUA-2025-05510.json
